version: '3'

services:
  redis:
    image: redis
    container_name: oidc-test-redis
    restart: unless-stopped
    ports:
    - 127.0.0.1:63792:6379
    volumes:
    - oidc-test-redis-data:/data

volumes:
  oidc-test-redis-data: